import { ReactComponent as AnchorIcon } from './assets/Anchor.svg';
import { ReactComponent as AnchorNoCircleIcon } from './assets/AnchorNoCircle.svg';
import { ReactComponent as APYIcon } from './assets/APY.svg';
import { ReactComponent as ArrowDownIcon } from './assets/ArrowDown.svg';
import { ReactComponent as BorrowAPRIcon } from './assets/BorrowAPR.svg';
import { ReactComponent as BorrowValueIcon } from './assets/BorrowValue.svg';
import { ReactComponent as CircleArrowRightIcon } from './assets/CircleArrowRight.svg';
import { ReactComponent as CollateralValueIcon } from './assets/CollateralValue.svg';
import { ReactComponent as DiscordIcon } from './assets/Discord.svg';
import { ReactComponent as LabtopIcon } from './assets/Labtop.svg';
import { ReactComponent as MenuIcon } from './assets/Menu.svg';
import { ReactComponent as MenuCloseIcon } from './assets/MenuClose.svg';
import { ReactComponent as WalletIcon } from './assets/Wallet.svg';
import { createMaterialIcon } from './createMaterialIcon';

export const Discord = createMaterialIcon(DiscordIcon);
export const Wallet = createMaterialIcon(WalletIcon);
export const ArrowDown = createMaterialIcon(ArrowDownIcon);
export const Anchor = createMaterialIcon(AnchorIcon);
export const AnchorNoCircle = createMaterialIcon(AnchorNoCircleIcon);
export const CircleArrowRight = createMaterialIcon(CircleArrowRightIcon);
export const Labtop = createMaterialIcon(LabtopIcon);
export const Menu = createMaterialIcon(MenuIcon);
export const MenuClose = createMaterialIcon(MenuCloseIcon);
export const APY = createMaterialIcon(APYIcon);
export const BorrowAPR = createMaterialIcon(BorrowAPRIcon);
export const BorrowValue = createMaterialIcon(BorrowValueIcon);
export const CollateralValue = createMaterialIcon(CollateralValueIcon);
