import { TERRA_QUERY_KEY } from '@terra-money/webapp-fns';
import { TxRefetchMap } from '@terra-money/webapp-provider';

export enum ANCHOR_TX_KEY {
  EARN_DEPOSIT = 'ANCHOR_TX_EARN_DEPOSIT',
  EARN_WITHDRAW = 'ANCHOR_TX_EARN_WITHDRAW',
  BORROW_BORROW = 'ANCHOR_TX_BORROW_BORROW',
  BORROW_REPAY = 'ANCHOR_TX_BORROW_BORROW',
  BORROW_PROVIDE_COLLATERAL = 'ANCHOR_TX_BORROW_BORROW',
  BORROW_REDEEM_COLLATERAL = 'ANCHOR_TX_BORROW_BORROW',
  BOND_MINT = 'ANCHOR_TX_BOND_MINT',
  BOND_BURN = 'ANCHOR_TX_BOND_BURN',
  BOND_SWAP = 'ANCHOR_TX_BOND_SWAP',
  BOND_CLAIM = 'ANCHOR_TX_BOND_CLAIM',
  BOND_WITHDRAW = 'ANCHOR_TX_BOND_WITHDRAW',
}

export enum ANCHOR_QUERY_KEY {
  EARN_EPOCH_STATES = 'ANCHOR_QUERY_EARN_EPOCH_STATES',
  EARN_APY_HISTORY = 'ANCHOR_QUERY_EARN_APY_HISTORY',
  EARN_TRANSACTION_HISTORY = 'ANCHOR_QUERY_EARN_TRANSACTION_HISTORY',
  BORROW_MARKET = 'ANCHOR_QUERY_BORROW_MARKET',
  BORROW_BORROWER = 'ANCHOR_QUERY_BORROW_BORROWER',
  BORROW_APY = 'ANCHOR_QUERY_BORROW_APY',
  BORROW_LIQUIDATION_PRICE = 'ANCHOR_QUERY_BORROW_LIQUIDATION_PRICE',
  BOND_BLUNA_EXCHANGE_RATE = 'ANCHOR_QUERY_BOND_EXHCNAGE_RATE',
  BOND_BLUNA_PRICE = 'ANCHOR_QUERY_BOND_BLUNA_PRICE',
  BOND_CLAIMABLE_REWARDS = 'ANCHOR_QUERY_BOND_CLAIMABLE_REWARDS',
  BOND_VALIDATORS = 'ANCHOR_QUERY_BOND_VALIDATORS',
  BOND_WITHDRAWABLE_AMOUNT = 'ANCHOR_QUERY_BOND_WITHDRAWABLE_AMOUNT',
}

export const ANCHOR_TX_REFETCH_MAP: TxRefetchMap = {
  [ANCHOR_TX_KEY.EARN_DEPOSIT]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.EARN_EPOCH_STATES,
    {
      queryKey: ANCHOR_QUERY_KEY.EARN_TRANSACTION_HISTORY,
      wait: 1000 * 3,
    },
  ],
  [ANCHOR_TX_KEY.EARN_WITHDRAW]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.EARN_EPOCH_STATES,
    {
      queryKey: ANCHOR_QUERY_KEY.EARN_TRANSACTION_HISTORY,
      wait: 1000 * 3,
    },
  ],
  [ANCHOR_TX_KEY.BORROW_BORROW]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.BORROW_MARKET,
    ANCHOR_QUERY_KEY.BORROW_BORROWER,
    ANCHOR_QUERY_KEY.BORROW_APY,
    ANCHOR_QUERY_KEY.BORROW_LIQUIDATION_PRICE,
  ],
  [ANCHOR_TX_KEY.BORROW_REPAY]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.BORROW_MARKET,
    ANCHOR_QUERY_KEY.BORROW_BORROWER,
    ANCHOR_QUERY_KEY.BORROW_APY,
    ANCHOR_QUERY_KEY.BORROW_LIQUIDATION_PRICE,
  ],
  [ANCHOR_TX_KEY.BORROW_PROVIDE_COLLATERAL]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.BORROW_MARKET,
    ANCHOR_QUERY_KEY.BORROW_BORROWER,
    ANCHOR_QUERY_KEY.BORROW_APY,
    ANCHOR_QUERY_KEY.BORROW_LIQUIDATION_PRICE,
  ],
  [ANCHOR_TX_KEY.BORROW_REDEEM_COLLATERAL]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.BORROW_MARKET,
    ANCHOR_QUERY_KEY.BORROW_BORROWER,
    ANCHOR_QUERY_KEY.BORROW_APY,
    ANCHOR_QUERY_KEY.BORROW_LIQUIDATION_PRICE,
  ],
  [ANCHOR_TX_KEY.BOND_MINT]: [TERRA_QUERY_KEY.TOKEN_BALANCES],
  [ANCHOR_TX_KEY.BOND_BURN]: [TERRA_QUERY_KEY.TOKEN_BALANCES],
  [ANCHOR_TX_KEY.BOND_SWAP]: [TERRA_QUERY_KEY.TOKEN_BALANCES],
  [ANCHOR_TX_KEY.BOND_CLAIM]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.BOND_CLAIMABLE_REWARDS,
  ],
  [ANCHOR_TX_KEY.BOND_WITHDRAW]: [
    TERRA_QUERY_KEY.TOKEN_BALANCES,
    ANCHOR_QUERY_KEY.BOND_WITHDRAWABLE_AMOUNT,
  ],
};
