[package]
name = "my-library"
version = "0.1.0"
authors = ["SSen <i@ssen.name>"]
edition = "2018"
description = "Test wasm pack"
license = "MIT"
repository = "https://github.com/Anchor-Protocol/anchor-web-app"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"