GET https://anchor-services.vercel.app/api/deposit
Accept: application/json

###

GET https://anchor-services.vercel.app/api/collaterals
Accept: application/json

###

GET https://anchor-services.vercel.app/api/market/ust
Accept: application/json

###

https://anchor-services.vercel.app/api/borrow
Accept: application/json

###

https://anchor-services.vercel.app/api/bassets/bluna
Accept: application/json